Add TypeScript typings
hgcummings/pixel-fonts pull request #1
Opened 2022-06-21 05:02 UTC by alexander-fenster

Hi @hgcummings,

Thanks for the library! I'm using it in my small hobby project that is written in TypeScript, and I needed to write these typings to make it possible. I realize it's a 6 years old project. If you're willing to publish an update with these types to NPM, I will really appreciate it! Otherwise, I can add this `.d.ts` to DefinitelyTyped repository if you prefer it that way.

Thank you!

2022-06-21 08:30 UTC, hgcummings requested changes
Hi Alexander. Thanks for the PR!

Looks good and I'm happy to merge it. Just one typo to fix first.

2022-06-21 08:30 UTC, hgcummings commented on index.d.ts
> +  slimbers: Font;
Typo here: the font name is "slumbers"

2022-06-21 09:14 UTC, alexander-fenster commented on index.d.ts
> +  slimbers: Font;
Oops, fixed, thank you!

2022-06-21 09:18 UTC, hgcummings approved these changes

2022-06-21 09:18 UTC, merged

2022-06-21 09:19 UTC, hgcummings commented
Merged. Thank you for the PR!

2022-06-21 18:37 UTC, alexander-fenster commented
@hgcummings Thank you Harry! Will you have a chance to release this to npm? Thank you!

2022-06-22 07:15 UTC, hgcummings commented
Yep, a bit busy yesterday but will publish a new version at some point today (UK time, so might be overnight for you).

2022-06-23 07:36 UTC, hgcummings commented
Published v1.6.0

Let me know if you encounter any issues using the new release.